CREATE TABLE exams (
    id VARCHAR(100) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    year SMALLINT,
    teacher_id UUID NOT NULL,
    duration_in_minutes INT DEFAULT 0,
    is_active BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_teacher
        FOREIGN KEY(teacher_id) 
        REFERENCES users(id)
        ON DELETE CASCADE
);